# Generated by Django 5.2 on 2025-04-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_platform_app', '0002_delete_homepage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.CharField(),
        ),
    ]
