# Generated by Django 5.2 on 2025-04-22 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_platform_app', '0004_course_prerequisites_course_what_you_will_learn'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
